### ISSUE TITLE
show visual feedback on zoom to current location button

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#19] opened 2013-07-07 06:53 UTC
When the current location is being tracked fill in icon but when user pans unfill icon to indicate current location is not being followed. For an example see the Apple Maps app. Also most other maps show this in the lower left.

**Comment by aaronbrethorst** [comment] 2015-12-04 07:48
@bbodenmiller can you clarify exactly what the issue is here?

**Comment by bbodenmiller** [comment] 2015-12-04 07:58
The details @yogipatel posted at https://github.com/OneBusAway/onebusaway-iphone/issues/432#issue-92819008. Location button should be solid when tracking users location and hallow when not tracking users location.

**Comment by aaronbrethorst** [comment] 2015-12-04 08:31
ah, ok, splendid. Closing as a dupe of #432

**Closed by aaronbrethorst** 2015-12-04 08:31 UTC
Labels: 0 - Backlog, enhancement, map
